[build-system]
requires = ["setuptools>=80.10.2"]
build-backend = "setuptools.build_meta"

[project]
name = "master-thesis"
version = "0.1.1"
description = "Fine-Tuning Pretrained Neural Networks for Structured Information Extraction"
authors = [
    { name = "Pirro Zani", email = "pirrozani@outlook.com" },
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pip>=26.0.1",
    "ruff>=0.15.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "unsloth>=2026.1.4",
    "pydantic>=2.12.5",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu130" },
]
torchvision = [
    { index = "pytorch-cu130" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.ruff]
include = ["*.py", "notebooks/*.ipynb"]

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
]
line-length = 88
indent-width = 4

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[tool.ruff.lint]
select = ["E", "F"]
ignore = []
