"""Pydantic models for entity type classification."""

from pydantic import BaseModel, Field

# Class labels for the binary classification task
COMPANY = 'company'
PERSON = 'person'
VALID_LABELS = (COMPANY, PERSON)


class EntityType(BaseModel):
    """Entity type label with plain-string serialization support."""

    label: str = Field(default='', description='Entity type: company or person')

    def to_output(self) -> str:
        """Serialize to plain-string output.

        Returns:
            The label string ('company', 'person', or '' when unset)
        """
        return self.label

    @classmethod
    def from_output(cls, output: str) -> 'EntityType':
        """Parse model output text into the nearest valid label.

        Normalizes the raw generation (lowercase, stripped) and maps it to a
        valid label. Unparseable or empty output yields an empty label ('')
        which downstream code treats as an invalid prediction. The output is
        never silently coerced to a default class.

        Args:
            output: Raw text generated by the model

        Returns:
            EntityType with a valid label, or an empty label if unparseable
        """
        if not output or not output.strip():
            return cls()

        text = output.strip().lower()

        # Exact match first (the model is trained to emit one word)
        for label in VALID_LABELS:
            if text == label:
                return cls(label=label)

        for label in VALID_LABELS:
            if label in text:
                return cls(label=label)

        return cls()

    def is_valid(self) -> bool:
        """Return whether the label is one of the valid classes.

        Returns:
            True if the label is 'company' or 'person', else False
        """
        return self.label in VALID_LABELS
